<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rewards</name>
   <tag></tag>
   <elementGuidId>6fd56068-f70f-467c-bd37-9f7639b6140f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div/div/nav/a[4]/div[2]/span/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Rewards&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>30ce44a5-a53b-4473-b989-cec63fb1c5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-1bxyjc6</value>
      <webElementGuid>c8dbaa02-4652-4a64-ac15-ad236167a3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rewards</value>
      <webElementGuid>e174f0cb-ed6a-4663-9302-0f3e8772db72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl css-8yyeyr&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-2.4 css-1rh4usm&quot;]/div[@class=&quot;MuiBox-root css-c6lz7k&quot;]/div[@class=&quot;css-10jtw9x&quot;]/nav[@class=&quot;MuiList-root MuiList-padding css-1dy0ggd&quot;]/a[@class=&quot;MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root css-1029anh&quot;]/div[@class=&quot;MuiListItemText-root css-1tsvksn&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 css-1bxyjc6&quot;]</value>
      <webElementGuid>53fff5a7-5f60-4003-90da-b5071408b9f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div/div/nav/a[4]/div[2]/span/p</value>
      <webElementGuid>d2dc0e9a-736d-4c0b-8ee8-bd51b0926267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[1]/following::p[7]</value>
      <webElementGuid>bcb5686e-e11c-4925-bb96-9b88ae988bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View as Admin'])[1]/preceding::p[2]</value>
      <webElementGuid>b9a731f8-1153-4eec-b738-6437df02ac00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays Goal'])[1]/preceding::p[3]</value>
      <webElementGuid>4d422689-ef34-45f5-bdfb-b48ab32178ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rewards']/parent::*</value>
      <webElementGuid>602cee25-ce44-426b-8fc2-0f68793ff581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div[2]/span/p</value>
      <webElementGuid>a3693e01-f11b-4a0b-82a9-5c798844383f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rewards' or . = 'Rewards')]</value>
      <webElementGuid>120ab7f9-a4e3-45e0-94b5-cb1e9feb87a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
