<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>135aa0b9-dcd3-445d-9ab1-2a84434e5545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[3]/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__next&quot;] iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>53b48ad1-f71c-4124-a015-9bf7948bee94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://alyve-web-v1-uat.vercel.app/store?v2=true&amp;token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzJhYTU1MTU3ODUwYWE1MTI2MDZiZDYzM2YyMDk5NzljNTg0MWI1OTVjMGViYThlZTI4M2Y1NDg5Nzk0MTJhODM3YjFkZDE4YjMzMTFkNzAiLCJpYXQiOjE3MTUwNjY5NDUuMTcyMTY0LCJuYmYiOjE3MTUwNjY5NDUuMTcyMTY4LCJleHAiOjE4NzI4MzMzNDUuMTYxNjU0LCJzdWIiOiI1NTMzOSIsInNjb3BlcyI6W119.HEPclK-5t5tLU42LtwVEG7f476tzniPbaJA-Yjg9WZbu5UWv6VSnh9Qrk-6LHvd6QpQ6rbhsrZhxQfvOSUYNGIR0XveFUoNcVpKmM4GS-u1ZlGIspUyss1R_CgEyHD31XwRPhPPOljO7LY2rVabPW8ejBnfW911n7m9F0LxLv1nlLfiHqAE-lgtCEXsoGTO1i_Qpe87f-yueVXhzFdFqW13edup3kSTxsod945Ixe7S3THozz9azGh-tnqWFRLgVw4qazirrc-gmTG19u0WMODfhuqTEnLlAderRqE7UHS7F2t9hMifUFLhXD4TdLnFXQVbCGltTNlv8zE_fPFPh4GBFNjudzvB_tKoRXfvuXT7jJbwGrTfROFljhQWuham9XmdTQr2RpqU49wRe5S-8v16gGvyC47p72A7UlR9V4w0_btVgoE7DFEceCtQyPCBGoKRleyoM1Kv1lIEl66Fp5hy1eo1YM--bvMS7Fjlu4KGuyB-8Z29tRLm49z8ZDngc0A5UCiitv1Hktqy_4hm2P4BzVKI_uGuVviZCgYqZTVmWVcHLzoWVHnyeiQEHRKKpQZeiI_fPVJ1u8-pVuPQ5mEzmkLoJZ3QfypTFfp8MVUDfPSNmNrsTxUaCJiv9XeNrrikffpZQbyLy8d0spWv5C5O1iBJbC9Vrp6hMYgcbFPI&amp;refresh=0</value>
      <webElementGuid>f05be484-33e3-4914-af59-91ae7f9f85e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl css-1vz2i80&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-lg-9.5 css-1evk3st&quot;]/div[@class=&quot;MuiBox-root css-1tnmow4&quot;]/iframe[1]</value>
      <webElementGuid>f6228863-daa1-42a9-ad56-8887f6f211ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[3]/div/iframe</value>
      <webElementGuid>9d1ccdfe-ddcc-4834-8b9a-1b70c7e88a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0f1bdb02-217d-47ea-b883-377579fb2916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://alyve-web-v1-uat.vercel.app/store?v2=true&amp;token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNzJhYTU1MTU3ODUwYWE1MTI2MDZiZDYzM2YyMDk5NzljNTg0MWI1OTVjMGViYThlZTI4M2Y1NDg5Nzk0MTJhODM3YjFkZDE4YjMzMTFkNzAiLCJpYXQiOjE3MTUwNjY5NDUuMTcyMTY0LCJuYmYiOjE3MTUwNjY5NDUuMTcyMTY4LCJleHAiOjE4NzI4MzMzNDUuMTYxNjU0LCJzdWIiOiI1NTMzOSIsInNjb3BlcyI6W119.HEPclK-5t5tLU42LtwVEG7f476tzniPbaJA-Yjg9WZbu5UWv6VSnh9Qrk-6LHvd6QpQ6rbhsrZhxQfvOSUYNGIR0XveFUoNcVpKmM4GS-u1ZlGIspUyss1R_CgEyHD31XwRPhPPOljO7LY2rVabPW8ejBnfW911n7m9F0LxLv1nlLfiHqAE-lgtCEXsoGTO1i_Qpe87f-yueVXhzFdFqW13edup3kSTxsod945Ixe7S3THozz9azGh-tnqWFRLgVw4qazirrc-gmTG19u0WMODfhuqTEnLlAderRqE7UHS7F2t9hMifUFLhXD4TdLnFXQVbCGltTNlv8zE_fPFPh4GBFNjudzvB_tKoRXfvuXT7jJbwGrTfROFljhQWuham9XmdTQr2RpqU49wRe5S-8v16gGvyC47p72A7UlR9V4w0_btVgoE7DFEceCtQyPCBGoKRleyoM1Kv1lIEl66Fp5hy1eo1YM--bvMS7Fjlu4KGuyB-8Z29tRLm49z8ZDngc0A5UCiitv1Hktqy_4hm2P4BzVKI_uGuVviZCgYqZTVmWVcHLzoWVHnyeiQEHRKKpQZeiI_fPVJ1u8-pVuPQ5mEzmkLoJZ3QfypTFfp8MVUDfPSNmNrsTxUaCJiv9XeNrrikffpZQbyLy8d0spWv5C5O1iBJbC9Vrp6hMYgcbFPI&amp;refresh=0']</value>
      <webElementGuid>e4818c45-28a1-4656-9072-33b38f4a86c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
