<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Challenges</name>
   <tag></tag>
   <elementGuidId>9e0fb38c-a141-4645-932c-d14cc7446d43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div/div/nav/a[3]/div[2]/span/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Challenges&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>48673e52-cce6-4ed8-beaa-0e466cf67420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-1bxyjc6</value>
      <webElementGuid>afbad600-8268-4fb8-8425-b8576a0e0f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Challenges</value>
      <webElementGuid>a9840fc9-84b4-4e19-86b7-98601fd358c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl css-8yyeyr&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-2.4 css-1rh4usm&quot;]/div[@class=&quot;MuiBox-root css-c6lz7k&quot;]/div[@class=&quot;css-10jtw9x&quot;]/nav[@class=&quot;MuiList-root MuiList-padding css-1dy0ggd&quot;]/a[@class=&quot;MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root css-1029anh&quot;]/div[@class=&quot;MuiListItemText-root css-1tsvksn&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 css-1bxyjc6&quot;]</value>
      <webElementGuid>0f8209d6-9b0b-4c03-9959-3995f70afaea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div/div/nav/a[3]/div[2]/span/p</value>
      <webElementGuid>a1f96ae8-77b4-4ae7-b514-20003a117533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[1]/following::p[6]</value>
      <webElementGuid>45089f14-0c29-4826-ac5e-e35dfb983dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View as Admin'])[1]/preceding::p[3]</value>
      <webElementGuid>30093605-6418-4081-a8b5-325f25726888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays Goal'])[1]/preceding::p[4]</value>
      <webElementGuid>24182ae2-1df5-430d-a04b-1e16eb6f02df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Challenges']/parent::*</value>
      <webElementGuid>37321813-3732-4d5c-9246-f238851e2f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div[2]/span/p</value>
      <webElementGuid>2ea0ed11-e90a-4e16-b484-0b26b5465b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Challenges' or . = 'Challenges')]</value>
      <webElementGuid>dd39b148-f02b-42f0-bc23-69c75394f0f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
