<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rewards</name>
   <tag></tag>
   <elementGuidId>6abe908e-a62d-4ebe-839e-8cc2013e5dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div/div/nav/a[4]/div[2]/span/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Rewards&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>00742e7b-d046-4acd-b0bd-7d6634cf6625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-1bxyjc6</value>
      <webElementGuid>5952024b-f51a-4efc-96e9-86343db60a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rewards</value>
      <webElementGuid>52e64bd7-abcc-43e8-b786-59c40d6d4c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl css-8yyeyr&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-1d3bbye&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-2.4 css-1rh4usm&quot;]/div[@class=&quot;MuiBox-root css-c6lz7k&quot;]/div[@class=&quot;css-10jtw9x&quot;]/nav[@class=&quot;MuiList-root MuiList-padding css-1dy0ggd&quot;]/a[@class=&quot;MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root css-1029anh&quot;]/div[@class=&quot;MuiListItemText-root css-1tsvksn&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 css-1bxyjc6&quot;]</value>
      <webElementGuid>a301be72-e30f-4d7b-8b31-80b2e0ac088d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div/div/nav/a[4]/div[2]/span/p</value>
      <webElementGuid>2a20e840-b405-4410-9025-015140706d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='H'])[1]/following::p[7]</value>
      <webElementGuid>7c9a877d-4a73-46cb-bb5b-7d32718d790c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View as Admin'])[1]/preceding::p[2]</value>
      <webElementGuid>2f7aaa7c-1459-4350-bac6-1ff4bbce9b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays Goal'])[1]/preceding::p[3]</value>
      <webElementGuid>1c970cd3-d558-4499-9a23-395b7f2a34d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rewards']/parent::*</value>
      <webElementGuid>f6a918b0-45bf-4f62-81b3-be703ae207f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div[2]/span/p</value>
      <webElementGuid>87a7222b-6fba-4263-bd70-4657c196eaa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rewards' or . = 'Rewards')]</value>
      <webElementGuid>1ac6b8a7-6213-4c7d-aefd-6d2f51a14ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
